const MINUTE = 60 * 1000;
const HOUR = 60 * MINUTE;
const DAY = 24 * HOUR;

export const SESSION_TTL_MS = 12 * HOUR;
export const PERSISTENT_SESSION_TTL_MS = 30 * DAY;

// Límite de intentos fallidos de login dentro de la ventana.
export const LOGIN_WINDOW_MS = 15 * MINUTE;
export const MAX_FAILED_LOGINS_PER_ACCOUNT = 5;
export const MAX_FAILED_LOGINS_PER_IP = 20;

export const RESET_TOKEN_TTL_MS = 20 * MINUTE;
export const RESET_WINDOW_MS = 15 * MINUTE;
export const MAX_RESET_REQUESTS_PER_ACCOUNT = 3;
export const MAX_RESET_REQUESTS_PER_IP = 10;

export const AUTH_EVENTS = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGIN_BLOCKED: "LOGIN_BLOCKED",
  LOGOUT: "LOGOUT",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_BLOCKED: "PASSWORD_RESET_BLOCKED",
  PASSWORD_RESET_COMPLETED: "PASSWORD_RESET_COMPLETED",
} as const;

export const STAFF_INVITATION_TTL_MS = 72 * HOUR;

export const STAFF_EVENTS = {
  INVITATION_CREATED: "STAFF_INVITATION_CREATED",
  INVITATION_REVOKED: "STAFF_INVITATION_REVOKED",
  INVITATION_ACCEPTED: "STAFF_INVITATION_ACCEPTED",
} as const;
